export default {
  getname: state =>  state.name,
  getyear_of_business: state =>  state.year_of_business,
  getbusiness_industriess: state =>  state.business_industriess,
  getis_owner: state =>  state.is_owner,
  getphone: state =>  state.phone,
  getemail: state =>  state.email,
  getsistem_dan_proses: state =>  state.sistem_dan_proses,
  getperforma_karyawan: state =>  state.performa_karyawan,
  getperforma_finansial: state =>  state.performa_finansial,
  getbilling_invoicing_dan_debitur: state =>  state.billing_invoicing_dan_debitur,
  getcash_flow: state =>  state.cash_flow,
  getcreditor_payment: state =>  state.creditor_payment,
  getwork_in_progress: state =>  state.work_in_progress,
  getproject_management: state =>  state.project_management,
  getquality: state =>  state.quality,
  getclient_servicing: state =>  state.client_servicing,
  getorganization_and_scheduling: state =>  state.organization_and_scheduling,
  getrisk_management: state =>  state.risk_management,
  getstaff_culture: state =>  state.staff_culture,
  getsustainability_and_reward: state =>  state.sustainability_and_reward,
  getbusiness_planning: state =>  state.business_planning,
  getgrowth_and_balance: state =>  state.growth_and_balance,
  getscreening: state =>  state.screening,
  getscore: state =>  state.score,
}