export default {
  name: '',
  year_of_business: '',
  business_industriess: '',
  is_owner: '',
  phone: '',
  email: '',
  sistem_dan_proses: '',
  performa_karyawan: '',
  performa_finansial: '',
  billing_invoicing_dan_debitur: '',
  cash_flow: '',
  creditor_payment: '',
  work_in_progress: '',
  project_management: '',
  quality: '',
  client_servicing: '',
  organization_and_scheduling: '',
  risk_management: '',
  staff_culture: '',
  sustainability_and_reward: '',
  business_planning: '',
  growth_and_balance: '',
  screening: [],
  score: '',
}